CREATE PROCEDURE [dbo].[SP_GRAVA_PRODUTOS]
	@CODIGO INT,
	@DESCRICAO VARCHAR(50),
	@VALOR FLOAT,
	@CATEGORIA VARCHAR(30),
	@IMAGEM VARBINARY(MAX)
AS
BEGIN
	IF (@CODIGO IS NULL) OR (@CODIGO = 0)
	BEGIN
		INSERT INTO PRODUTOS
		(
			DESCRICAO,
			VALOR,
			CATEGORIA,
			IMAGEM
		)
		VALUES
		(
			@DESCRICAO,
			@VALOR,
			@CATEGORIA,
			@IMAGEM
		)
	END
	ELSE
	BEGIN
		UPDATE PRODUTOS SET
			DESCRICAO = @DESCRICAO,
			VALOR = @VALOR,
			CATEGORIA = @CATEGORIA,
			IMAGEM = @IMAGEM
		WHERE CODIGO = @CODIGO
	END
END
