CREATE DATABASE CADASTRO
GO
USE CADASTRO

CREATE TABLE PRODUTOS
(
CODIGO INT IDENTITY NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL,
VALOR FLOAT NOT NULL,
CATEGORIA VARCHAR(30) NULL,
IMAGEM  VARBINARY(MAX) NULL,

CONSTRAINT PK_PRODUTOS PRIMARY KEY (CODIGO)
)